services:
  test-db:
    image: ankane/pgvector:latest
    container_name: radar-test-db
    environment:
      POSTGRES_DB: radar-test-db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - "5433:5432"
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - test-network

networks:
  test-network: